### PR TITLE
Add wrapper for writing assignments

### PR DESCRIPTION
**Pull request by zertosh**
RFC: If this code looks reasonable, I will flesh out the documentation.

### CODE REVIEW

**Comment by dtolnay** [comment]
Looks reasonable :+1:

**Comment by zertosh** [comment]
Removed the dedicated tests in favor of doctests

**Review by dtolnay — APPROVED** [review]
Thanks!

**Comment by dtolnay** [comment]
Published in serde_starlark 0.1.11.

**Pull request merged**
